version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/save-cache      
      - run:
          name: Install sdl2 dependencies
          command:
            sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl1.2-dev libsmpeg-dev python-numpy subversion libportmidi-dev ffmpeg libswscale-dev libavformat-dev libavcodec-dev
      - run:
          name: Install Python dependencies
          command: 
            pip install -r requirements.txt
      - run:
          name: Test
          command:
            python test_main.py -v
            
workflows:
  main:
    jobs:
      - build-and-test
