version: 2.1

orbs:
  python: circleci/python@0.2.1
  
dependencies:
  pre:
    - pip install --upgrade pip
    - pip install --upgrade 
    - if [ -e requirements.txt ]; then pip install -r requirements.txt;else pip install -r requirements.pip;fi

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/save-cache
      - run:
          name: Test
            command:
              python test_main.py -v
            
workflows:
  main:
    jobs:
      - build-and-test
