version: 2.1

orbs:
  python: circleci/python@0.2.1
  
dependencies:
  pre:
    - sudo apt-get update
    - sudo apt-get install -y python-pygame

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python test_main.py -v
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
